name: Build and Push

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push images to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check it out
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          pixelkiri/devkitpro-alpine-switch
          pixelkiri/devkitpro-alpine-ppc
          pixelkiri/devkitpro-alpine-arm
    - name: Build and push devkitpro-alpine-switch image
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.alpine-switch
        push: true
        tags: pixelkiri/devkitpro-alpine-switch:latest
        cache-from: type=registry,ref=pixelkiri/devkitpro-alpine-switch:latest
        cache-to: type=inline
    - name: Build and push devkitpro-alpine-ppc image
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.alpine-ppc
        push: true
        tags: pixelkiri/devkitpro-alpine-ppc:latest
        cache-from: type=registry,ref=pixelkiri/devkitpro-alpine-ppc:latest
        cache-to: type=inline
    - name: Build and push devkitpro-alpine-arm image
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.alpine-arm
        push: true
        tags: pixelkiri/devkitpro-alpine-arm:latest
        cache-from: type=registry,ref=pixelkiri/devkitpro-alpine-arm:latest
        cache-to: type=inline
